In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform

df_books = pd.read_csv('C:/Users/Kacper/.spyder-py3/files/input/genres.csv')
df_books.head()

,book_id,authors,original_title,genre,small_image_url
0,2767052,Suzanne Collins,The Hunger Games,"fiction, fantasy",https://images.gr-assets.com/books/1447303603s...
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Philosopher's Stone,"fantasy, fiction",https://images.gr-assets.com/books/1474154022s...
2,41865,Stephenie Meyer,Twilight,"fantasy, fiction",https://images.gr-assets.com/books/1361039443s...
3,2657,Harper Lee,To Kill a Mockingbird,"classics, fiction",https://images.gr-assets.com/books/1361975680s...
4,4671,F. Scott Fitzgerald,The Great Gatsby,"classics, fiction",https://images.gr-assets.com/books/1490528560s...

In [2]:
df_books['genre'] = df_books['genre'].str.split(',')
df_books.head()

,book_id,authors,original_title,genre,small_image_url
0,2767052,Suzanne Collins,The Hunger Games,"[fiction, fantasy]",https://images.gr-assets.com/books/1447303603s...
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Philosopher's Stone,"[fantasy, fiction]",https://images.gr-assets.com/books/1474154022s...
2,41865,Stephenie Meyer,Twilight,"[fantasy, fiction]",https://images.gr-assets.com/books/1361039443s...
3,2657,Harper Lee,To Kill a Mockingbird,"[classics, fiction]",https://images.gr-assets.com/books/1361975680s...
4,4671,F. Scott Fitzgerald,The Great Gatsby,"[classics, fiction]",https://images.gr-assets.com/books/1490528560s...

In [3]:
df_books_genre = df_books[['original_title', 'genre']]
df_books_genre = df_books_genre.explode('genre').reset_index(drop=True)
df_books_genre.head(8)

                             original_title     genre
0                          The Hunger Games   fiction
1                          The Hunger Games   fantasy
2  Harry Potter and the Philosopher's Stone   fantasy
3  Harry Potter and the Philosopher's Stone   fiction
4                                  Twilight   fantasy
5                                  Twilight   fiction
6                     To Kill a Mockingbird  classics
7                     To Kill a Mockingbird   fiction

In [4]:
book_cross_table = pd.crosstab(df_books_genre['original_title'], df_books_genre['genre'])
book_cross_table.head()

genre,art,biography,business,christian,classics,comics,contemporary,cookbooks,crime,ebooks,...,poetry,psychology,religion,romance,science,spirituality,sports,suspense,thriller,travel
original_title,,,,,,,,,,,,,,,,,,,,,
,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A Monster Calls,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animal Farm & 1984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Burned (Burned, #1)",0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Call the midwife : a true story of the East End in the 1950s,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
distances = pdist(book_cross_table.values, metric='jaccard')
similarity_array = 1 - squareform(distances)

similarity_df = pd.DataFrame(similarity_array, index=book_cross_table.index, columns=book_cross_table.index)

similarity_df.head()

original_title,,A Monster Calls,Animal Farm & 1984,"Burned (Burned, #1)",Call the midwife : a true story of the East End in the 1950s,"Carry On, Warrior: Thoughts on Life Unarmed",Carter Beats the Devil,Crown of Shadows,Daemon,De Imitatione Christi,...,電撃デイジー 1,青の祓魔師 1,青の祓魔師 2,高校デビュー 1,黑暗森林,黒執事 I [Kuroshitsuji I],黒執事 II [Kuroshitsuji II],黒執事 III [Kuroshitsuji III],엄마를 부탁해,채식주의자
original_title,,,,,,,,,,,,,,,,,,,,,
,1.0,0.000000,0.000000,0.000000,0.0,0.0,0.333333,0.0,1.0,0.0,...,0.0,0.333333,0.333333,0.0,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
A Monster Calls,0.0,1.000000,0.333333,0.333333,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Animal Farm & 1984,0.0,0.333333,1.000000,0.333333,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
"Burned (Burned, #1)",0.0,0.333333,0.333333,1.000000,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Call the midwife : a true story of the East End in the 1950s,0.0,0.000000,0.000000,0.000000,1.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
id = 1

similarity_series = similarity_df.loc[df_books[df_books.book_id == id]['original_title'].values[0]]

ordered_similarities = similarity_series.sort_values(ascending=False)

print('Using Jaccard similarity')
print('Similar books to :', df_books[df_books.book_id == id]['original_title'].values[0])
ordered_similarities.head()

Using Jaccard similarity
Similar books to : Harry Potter and the Half-Blood Prince

original_title
Stone of Farewell               1.0
The Indian in the Cupboard      1.0
The Invisible Library           1.0
Captain's Fury                  1.0
The Invasion of the Tearling    1.0
Name: Harry Potter and the Half-Blood Prince, dtype: float64